version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: db_imtiaz
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
